Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
engine = create_engine("mysql+pymysql://root:@localhost/ecoli")
df = pd.read_sql("SELECT * FROM ecoli;", engine) 
------------------


[1;31m--------------------------------------------------------------------------[0m
[1;31mConnectionRefusedError[0m                   Traceback (most recent call last)
File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py:661[0m, in [0;36mConnection.connect[1;34m(self, sock)[0m
[0;32m    660[0m [38;5;28;01mtry[39;00m:
[1;32m--> 661[0m     sock [38;5;241m=[39m socket[38;5;241m.[39mcreate_connection(
[0;32m    662[0m         ([38;5;28mself[39m[38;5;241m.[39mhost, [38;5;28mself[39m[38;5;241m.[39mport), [38;5;28mself[39m[38;5;241m.[39mconnect_timeout, [38;5;241m*[39m[38;5;241m*[39mkwargs
[0;32m    663[0m     )
[0;32m    664[0m     [38;5;28;01mbreak[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\socket.py:845[0m, in [0;36mcreate_connection[1;34m(address, timeout, source_address)[0m
[0;32m    844[0m [38;5;28;01mtry[39;00m:
[1;32m--> 845[0m     [38;5;28;01mraise[39;00m err
[0;32m    846[0m [38;5;28;01mfinally[39;00m:
[0;32m    847[0m     [38;5;66;03m# Break explicitly a reference cycle[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\socket.py:833[0m, in [0;36mcreate_connection[1;34m(address, timeout, source_address)[0m
[0;32m    832[0m     sock[38;5;241m.[39mbind(source_address)
[1;32m--> 833[0m [43msock[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43msa[49m[43m)[49m
[0;32m    834[0m [38;5;66;03m# Break explicitly a reference cycle[39;00m

[1;31mConnectionRefusedError[0m: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

[1;31mOperationalError[0m                         Traceback (most recent call last)
File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:143[0m, in [0;36mConnection.__init__[1;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[0;32m    142[0m [38;5;28;01mtry[39;00m:
[1;32m--> 143[0m     [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[0;32m    144[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:3301[0m, in [0;36mEngine.raw_connection[1;34m(self)[0m
[0;32m   3280[0m [38;5;250m[39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[0;32m   3281[0m 
[0;32m   3282[0m [38;5;124;03mThe returned object is a proxied version of the DBAPI[39;00m
[1;32m   (...)[0m
[0;32m   3299[0m 
[0;32m   3300[0m [38;5;124;03m"""[39;00m
[1;32m-> 3301[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:447[0m, in [0;36mPool.connect[1;34m(self)[0m
[0;32m    440[0m [38;5;250m[39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[0;32m    441[0m 
[0;32m    442[0m [38;5;124;03mThe connection is instrumented such that when its[39;00m
[1;32m   (...)[0m
[0;32m    445[0m 
[0;32m    446[0m [38;5;124;03m"""[39;00m
[1;32m--> 447[0m [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:1264[0m, in [0;36m_ConnectionFairy._checkout[1;34m(cls, pool, threadconns, fairy)[0m
[0;32m   1263[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[1;32m-> 1264[0m     fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[0;32m   1266[0m     [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:711[0m, in [0;36m_ConnectionRecord.checkout[1;34m(cls, pool)[0m
[0;32m    710[0m [38;5;28;01melse[39;00m:
[1;32m--> 711[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[0;32m    713[0m [38;5;28;01mtry[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py:177[0m, in [0;36mQueuePool._do_get[1;34m(self)[0m
[0;32m    176[0m [38;5;28;01mexcept[39;00m:
[1;32m--> 177[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[0;32m    178[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py:224[0m, in [0;36msafe_reraise.__exit__[1;34m(self, type_, value, traceback)[0m
[0;32m    223[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m--> 224[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[0;32m    225[0m [38;5;28;01melse[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py:175[0m, in [0;36mQueuePool._do_get[1;34m(self)[0m
[0;32m    174[0m [38;5;28;01mtry[39;00m:
[1;32m--> 175[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[0;32m    176[0m [38;5;28;01mexcept[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:388[0m, in [0;36mPool._create_connection[1;34m(self)[0m
[0;32m    386[0m [38;5;250m[39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[1;32m--> 388[0m [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:673[0m, in [0;36m_ConnectionRecord.__init__[1;34m(self, pool, connect)[0m
[0;32m    672[0m [38;5;28;01mif[39;00m connect:
[1;32m--> 673[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[0;32m    674[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:899[0m, in [0;36m_ConnectionRecord.__connect[1;34m(self)[0m
[0;32m    898[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[1;32m--> 899[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[0;32m    900[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py:224[0m, in [0;36msafe_reraise.__exit__[1;34m(self, type_, value, traceback)[0m
[0;32m    223[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m--> 224[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[0;32m    225[0m [38;5;28;01melse[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:895[0m, in [0;36m_ConnectionRecord.__connect[1;34m(self)[0m
[0;32m    894[0m [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[1;32m--> 895[0m [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[0;32m    896[0m pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\create.py:661[0m, in [0;36mcreate_engine.<locals>.connect[1;34m(connection_record)[0m
[0;32m    659[0m             [38;5;28;01mreturn[39;00m connection
[1;32m--> 661[0m [38;5;28;01mreturn[39;00m dialect[38;5;241m.[39mconnect([38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py:629[0m, in [0;36mDefaultDialect.connect[1;34m(self, *cargs, **cparams)[0m
[0;32m    627[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs: Any, [38;5;241m*[39m[38;5;241m*[39mcparams: Any) [38;5;241m-[39m[38;5;241m>[39m DBAPIConnection:
[0;32m    628[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[1;32m--> 629[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mconnect([38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py:365[0m, in [0;36mConnection.__init__[1;34m(self, user, password, host, database, unix_socket, port, charset, collation, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_key_password, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[0;32m    364[0m [38;5;28;01melse[39;00m:
[1;32m--> 365[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py:723[0m, in [0;36mConnection.connect[1;34m(self, sock)[0m
[0;32m    722[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[1;32m--> 723[0m     [38;5;28;01mraise[39;00m exc
[0;32m    725[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[0;32m    726[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[0;32m    727[0m [38;5;66;03m# So just reraise it.[39;00m

[1;31mOperationalError[0m: (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")

The above exception was the direct cause of the following exception:

[1;31mOperationalError[0m                         Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m engine [38;5;241m=[39m create_engine([38;5;124m"[39m[38;5;124mmysql+pymysql://root:@localhost/ecoli[39m[38;5;124m"[39m)
[1;32m----> 2[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_sql[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mSELECT * FROM ecoli;[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mengine[49m[43m)[49m 

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\sql.py:652[0m, in [0;36mread_sql[1;34m(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize, dtype_backend, dtype)[0m
[0;32m    649[0m     dtype_backend [38;5;241m=[39m [38;5;124m"[39m[38;5;124mnumpy[39m[38;5;124m"[39m  [38;5;66;03m# type: ignore[assignment][39;00m
[0;32m    650[0m [38;5;28;01massert[39;00m dtype_backend [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m lib[38;5;241m.[39mno_default
[1;32m--> 652[0m [38;5;28;01mwith[39;00m [43mpandasSQL_builder[49m[43m([49m[43mcon[49m[43m)[49m [38;5;28;01mas[39;00m pandas_sql:
[0;32m    653[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(pandas_sql, SQLiteDatabase):
[0;32m    654[0m         [38;5;28;01mreturn[39;00m pandas_sql[38;5;241m.[39mread_query(
[0;32m    655[0m             sql,
[0;32m    656[0m             index_col[38;5;241m=[39mindex_col,
[1;32m   (...)[0m
[0;32m    662[0m             dtype[38;5;241m=[39mdtype,
[0;32m    663[0m         )

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\sql.py:851[0m, in [0;36mpandasSQL_builder[1;34m(con, schema, need_transaction)[0m
[0;32m    848[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mUsing URI string without sqlalchemy installed.[39m[38;5;124m"[39m)
[0;32m    850[0m [38;5;28;01mif[39;00m sqlalchemy [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;28misinstance[39m(con, ([38;5;28mstr[39m, sqlalchemy[38;5;241m.[39mengine[38;5;241m.[39mConnectable)):
[1;32m--> 851[0m     [38;5;28;01mreturn[39;00m [43mSQLDatabase[49m[43m([49m[43mcon[49m[43m,[49m[43m [49m[43mschema[49m[43m,[49m[43m [49m[43mneed_transaction[49m[43m)[49m
[0;32m    853[0m warnings[38;5;241m.[39mwarn(
[0;32m    854[0m     [38;5;124m"[39m[38;5;124mpandas only supports SQLAlchemy connectable (engine/connection) or [39m[38;5;124m"[39m
[0;32m    855[0m     [38;5;124m"[39m[38;5;124mdatabase string URI or sqlite3 DBAPI2 connection. Other DBAPI2 [39m[38;5;124m"[39m
[1;32m   (...)[0m
[0;32m    858[0m     stacklevel[38;5;241m=[39mfind_stack_level(),
[0;32m    859[0m )
[0;32m    860[0m [38;5;28;01mreturn[39;00m SQLiteDatabase(con)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\sql.py:1576[0m, in [0;36mSQLDatabase.__init__[1;34m(self, con, schema, need_transaction)[0m
[0;32m   1574[0m     [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39mcallback(con[38;5;241m.[39mdispose)
[0;32m   1575[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(con, Engine):
[1;32m-> 1576[0m     con [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39menter_context([43mcon[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m)
[0;32m   1577[0m [38;5;28;01mif[39;00m need_transaction [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m con[38;5;241m.[39min_transaction():
[0;32m   1578[0m     [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39menter_context(con[38;5;241m.[39mbegin())

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:3277[0m, in [0;36mEngine.connect[1;34m(self)[0m
[0;32m   3254[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m Connection:
[0;32m   3255[0m [38;5;250m    [39m[38;5;124;03m"""Return a new :class:`_engine.Connection` object.[39;00m
[0;32m   3256[0m 
[0;32m   3257[0m [38;5;124;03m    The :class:`_engine.Connection` acts as a Python context manager, so[39;00m
[1;32m   (...)[0m
[0;32m   3274[0m 
[0;32m   3275[0m [38;5;124;03m    """[39;00m
[1;32m-> 3277[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connection_cls[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:145[0m, in [0;36mConnection.__init__[1;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[0;32m    143[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m engine[38;5;241m.[39mraw_connection()
[0;32m    144[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[1;32m--> 145[0m         [43mConnection[49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception_noconnection[49m[43m([49m
[0;32m    146[0m [43m            [49m[43merr[49m[43m,[49m[43m [49m[43mdialect[49m[43m,[49m[43m [49m[43mengine[49m
[0;32m    147[0m [43m        [49m[43m)[49m
[0;32m    148[0m         [38;5;28;01mraise[39;00m
[0;32m    149[0m [38;5;28;01melse[39;00m:

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:2440[0m, in [0;36mConnection._handle_dbapi_exception_noconnection[1;34m(cls, e, dialect, engine, is_disconnect, invalidate_pool_on_disconnect, is_pre_ping)[0m
[0;32m   2438[0m [38;5;28;01melif[39;00m should_wrap:
[0;32m   2439[0m     [38;5;28;01massert[39;00m sqlalchemy_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m-> 2440[0m     [38;5;28;01mraise[39;00m sqlalchemy_exception[38;5;241m.[39mwith_traceback(exc_info[[38;5;241m2[39m]) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01me[39;00m
[0;32m   2441[0m [38;5;28;01melse[39;00m:
[0;32m   2442[0m     [38;5;28;01massert[39;00m exc_info[[38;5;241m1[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:143[0m, in [0;36mConnection.__init__[1;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[0;32m    141[0m [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    142[0m     [38;5;28;01mtry[39;00m:
[1;32m--> 143[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[0;32m    144[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[0;32m    145[0m         Connection[38;5;241m.[39m_handle_dbapi_exception_noconnection(
[0;32m    146[0m             err, dialect, engine
[0;32m    147[0m         )

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\base.py:3301[0m, in [0;36mEngine.raw_connection[1;34m(self)[0m
[0;32m   3279[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mraw_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[0;32m   3280[0m [38;5;250m    [39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[0;32m   3281[0m 
[0;32m   3282[0m [38;5;124;03m    The returned object is a proxied version of the DBAPI[39;00m
[1;32m   (...)[0m
[0;32m   3299[0m 
[0;32m   3300[0m [38;5;124;03m    """[39;00m
[1;32m-> 3301[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:447[0m, in [0;36mPool.connect[1;34m(self)[0m
[0;32m    439[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[0;32m    440[0m [38;5;250m    [39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[0;32m    441[0m 
[0;32m    442[0m [38;5;124;03m    The connection is instrumented such that when its[39;00m
[1;32m   (...)[0m
[0;32m    445[0m 
[0;32m    446[0m [38;5;124;03m    """[39;00m
[1;32m--> 447[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:1264[0m, in [0;36m_ConnectionFairy._checkout[1;34m(cls, pool, threadconns, fairy)[0m
[0;32m   1256[0m [38;5;129m@classmethod[39m
[0;32m   1257[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_checkout[39m(
[0;32m   1258[0m     [38;5;28mcls[39m,
[1;32m   (...)[0m
[0;32m   1261[0m     fairy: Optional[_ConnectionFairy] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m   1262[0m ) [38;5;241m-[39m[38;5;241m>[39m _ConnectionFairy:
[0;32m   1263[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[1;32m-> 1264[0m         fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[0;32m   1266[0m         [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m   1267[0m             threadconns[38;5;241m.[39mcurrent [38;5;241m=[39m weakref[38;5;241m.[39mref(fairy)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:711[0m, in [0;36m_ConnectionRecord.checkout[1;34m(cls, pool)[0m
[0;32m    709[0m     rec [38;5;241m=[39m cast(_ConnectionRecord, pool[38;5;241m.[39m_do_get())
[0;32m    710[0m [38;5;28;01melse[39;00m:
[1;32m--> 711[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[0;32m    713[0m [38;5;28;01mtry[39;00m:
[0;32m    714[0m     dbapi_connection [38;5;241m=[39m rec[38;5;241m.[39mget_connection()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py:177[0m, in [0;36mQueuePool._do_get[1;34m(self)[0m
[0;32m    175[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[0;32m    176[0m [38;5;28;01mexcept[39;00m:
[1;32m--> 177[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[0;32m    178[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()
[0;32m    179[0m     [38;5;28;01mraise[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py:224[0m, in [0;36msafe_reraise.__exit__[1;34m(self, type_, value, traceback)[0m
[0;32m    222[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m    223[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m--> 224[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[0;32m    225[0m [38;5;28;01melse[39;00m:
[0;32m    226[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\impl.py:175[0m, in [0;36mQueuePool._do_get[1;34m(self)[0m
[0;32m    173[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_inc_overflow():
[0;32m    174[0m     [38;5;28;01mtry[39;00m:
[1;32m--> 175[0m         [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[0;32m    176[0m     [38;5;28;01mexcept[39;00m:
[0;32m    177[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:388[0m, in [0;36mPool._create_connection[1;34m(self)[0m
[0;32m    385[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_create_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m ConnectionPoolEntry:
[0;32m    386[0m [38;5;250m    [39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[1;32m--> 388[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:673[0m, in [0;36m_ConnectionRecord.__init__[1;34m(self, pool, connect)[0m
[0;32m    671[0m [38;5;28mself[39m[38;5;241m.[39m__pool [38;5;241m=[39m pool
[0;32m    672[0m [38;5;28;01mif[39;00m connect:
[1;32m--> 673[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[0;32m    674[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:899[0m, in [0;36m_ConnectionRecord.__connect[1;34m(self)[0m
[0;32m    897[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    898[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[1;32m--> 899[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[0;32m    900[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)
[0;32m    901[0m [38;5;28;01melse[39;00m:
[0;32m    902[0m     [38;5;66;03m# in SQLAlchemy 1.4 the first_connect event is not used by[39;00m
[0;32m    903[0m     [38;5;66;03m# the engine, so this will usually not be set[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py:224[0m, in [0;36msafe_reraise.__exit__[1;34m(self, type_, value, traceback)[0m
[0;32m    222[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m    223[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m--> 224[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[0;32m    225[0m [38;5;28;01melse[39;00m:
[0;32m    226[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\pool\base.py:895[0m, in [0;36m_ConnectionRecord.__connect[1;34m(self)[0m
[0;32m    893[0m [38;5;28;01mtry[39;00m:
[0;32m    894[0m     [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[1;32m--> 895[0m     [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[0;32m    896[0m     pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)
[0;32m    897[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\create.py:661[0m, in [0;36mcreate_engine.<locals>.connect[1;34m(connection_record)[0m
[0;32m    658[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[0;32m    659[0m             [38;5;28;01mreturn[39;00m connection
[1;32m--> 661[0m [38;5;28;01mreturn[39;00m dialect[38;5;241m.[39mconnect([38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\sqlalchemy\engine\default.py:629[0m, in [0;36mDefaultDialect.connect[1;34m(self, *cargs, **cparams)[0m
[0;32m    627[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs: Any, [38;5;241m*[39m[38;5;241m*[39mcparams: Any) [38;5;241m-[39m[38;5;241m>[39m DBAPIConnection:
[0;32m    628[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[1;32m--> 629[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mconnect([38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams)

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py:365[0m, in [0;36mConnection.__init__[1;34m(self, user, password, host, database, unix_socket, port, charset, collation, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_key_password, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[0;32m    363[0m     [38;5;28mself[39m[38;5;241m.[39m_sock [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m    364[0m [38;5;28;01melse[39;00m:
[1;32m--> 365[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\connections.py:723[0m, in [0;36mConnection.connect[1;34m(self, sock)[0m
[0;32m    721[0m     [38;5;28;01mif[39;00m DEBUG:
[0;32m    722[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[1;32m--> 723[0m     [38;5;28;01mraise[39;00m exc
[0;32m    725[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[0;32m    726[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[0;32m    727[0m [38;5;66;03m# So just reraise it.[39;00m
[0;32m    728[0m [38;5;28;01mraise[39;00m

[1;31mOperationalError[0m: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] No connection could be made because the target machine actively refused it)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

